### ISSUE TITLE
Error 456?

### ISSUE THREAD

**Issue by Blunderchips** [Kulbear/stock-prediction-rnn#3]
I am getting the following error when running fetch_data.py

[Getting data:]HTTP Error 456:
HTTP Error 456:
HTTP Error 456:
Traceback (most recent call last):
  File "fetch_data.py", line 52, in <module>
    get_all_history('000002', start='1995-01-01')
  File "fetch_data.py", line 47, in get_all_history
    df = ts.get_h_data(stock_index, start=start, autype=autype)
  File "/usr/local/lib/python3.5/dist-packages/tushare/stock/trading.py", line 432, in get_h_data
    retry_count, pause)
  File "/usr/local/lib/python3.5/dist-packages/tushare/stock/trading.py", line 572, in _parse_fq_data
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
OSError: 获取失败，请检查网络.

Any advice?

**Comment by artsmn** [comment]
I have the same errors, did you fix it?
