### ISSUE TITLE
HTTP Error 456 (run fetch_data.py)

### ISSUE THREAD

**Issue by smileyung** [Kulbear/stock-prediction-rnn#6]
python fetch_data.py
/home/smilewater/anaconda3/envs/tensorflow-gpu/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
[Getting data:]###################################################HTTP Error 456:
#HTTP Error 456:
HTTP Error 456:
HTTP Error 456:
Traceback (most recent call last):
  File "fetch_data.py", line 52, in <module>
    get_all_history('000002', start='1995-01-01')
  File "fetch_data.py", line 47, in get_all_history
    df = ts.get_h_data(stock_index, start=start, autype=autype)
  File "/home/smilewater/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tushare/stock/trading.py", line 440, in get_h_data
    retry_count, pause)
  File "/home/smilewater/anaconda3/envs/tensorflow-gpu/lib/python3.6/site-packages/tushare/stock/trading.py", line 572, in _parse_fq_data
    raise IOError(ct.NETWORK_URL_ERROR_MSG)
OSError: 获取失败，请检查网络.

**Comment by artsmn** [comment]
Did you find any solutions?
